lab_1/pythonProject/mysite/mysite/urls.py
from django.views.generic import RedirectView

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', RedirectView.as_view(url='/polls/', permanent=True)),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lab_1/pythonProject/mysite/polls/urls.py
from django.urls import path

from . import views


app_name = 'polls'
urlpatterns = [
    path('', views.Home.as_view(), name='home_page'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('register/', views.Register.as_view(), name='register'),
    path('user/<int:pk>/', views.UserDetail.as_view(), name='log_user'),
    path('user/<int:pk>/update', views.UserUpdate.as_view(), name='update_user'),
    path('user/<int:pk>/delete', views.UserDelete.as_view(), name='delete_user')
]

lab_1/pythonProject/mysite/polls/models.py
import datetime

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone


class NewUser(AbstractUser):
    photo_avatar = models.ImageField(max_length=254, verbose_name='Avatar', upload_to='media/avatarka', blank=False)


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    description = models.TextField(max_length=4000)
    brief_description = models.TextField(max_length=300)
    question_vote = models.IntegerField(default=0)
    pub_date = models.DateTimeField('date published')
    photo = models.ImageField(max_length=254, upload_to='media/question', blank=True)

    @property
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

    def get_percent(self):
        percent = self.votes * 100 / self.question.question_vote
        return percent


class Vote(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(NewUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.question.question_text

lab_1/pythonProject/mysite/polls/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from polls.models import NewUser


class RegisterUser(UserCreationForm):
    class Meta:
        model = NewUser
        fields = ['username', 'password1', 'password2', 'photo_avatar']


lab_1/pythonProject/mysite/polls/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import CreateView

from .forms import RegisterUser
from .models import Question, Choice, Vote, NewUser
from django.template import loader
from django.urls import reverse, reverse_lazy
from django.views import generic


class Home(generic.ListView):
    template_name = 'polls/home_page.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_object(self, queryset=None):
        question = super(DetailView, self).get_object(queryset)
        if question.was_published_recently or self.request.user.is_staff:
            return question
        else:
            raise PermissionDenied()


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "СДЕЛАЙТЕ ВЫБОР"
        })
    else:
        if Vote.objects.filter(question=question, user=request.user):
            return render(request, 'polls/detail.html', {
                'question': question,
                'error_message': 'ПРОГОЛОСОВАТЬ МОЖНО ТОЛЬКО ОДИН РАЗ'
            })
        else:
            question.question_vote += 1
            question.save()
            selected_choice.votes += 1
            selected_choice.save()
            user_voted = Vote.objects.create(question=question, user=request.user)
            user_voted.save()
            return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


class Register(CreateView):
    model = NewUser
    template_name = 'registration/register.html'
    form_class = RegisterUser
    success_url = reverse_lazy('login')
    success_page = 'registration'


class UserDetail(LoginRequiredMixin, generic.DetailView):
    model = NewUser
    template_name = 'polls/log_user.html'


class UserUpdate(LoginRequiredMixin, generic.UpdateView):
    model = NewUser
    template_name = 'polls/update_user.html'
    success_url = '/'
    fields = ('username', 'photo_avatar')

    def get_object(self, queryset=None):
        objs = super(UserUpdate, self).get_object(queryset)
        if objs != self.request.user:
            raise PermissionDenied()
        else:
            return self.request.user


class UserDelete(LoginRequiredMixin, generic.DeleteView):
    model = NewUser
    template_name = 'polls/delete_user.html'
    success_url = reverse_lazy('polls:home_page')


lab_1/pythonProject/mysite/polls/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
{% block sidebar %}

<nav class=" py-10  ">
    <a class=" px-10"   href="{% url 'polls:home_page' %}">ГЛАВНАЯ СТРАНИЦА</a>
    {% if user.is_authenticated %}
    <a class=" px-10" href="{% url 'logout' %}">ВЫХОД{{ user.login }}</a>
    <a class=" px-10" href="{% url 'polls:log_user' request.user.id %}">МОЯ СТРАНИЦА</a>
    {% else %}
    <a class="px-10" href="{% url 'login' %}">ВХОД</a>
    <a class="px-10" href="{% url 'polls:register' %}">РЕГИСТРАЦИЯ</a>
    {% endif %}
</nav>

{% endblock %}

{% block content %}

{% endblock %}

</body>
</html>

lab_1/pythonProject/mysite/polls/templates/polls/delete_user.html
{% extends 'base.html' %}



{% block content %}

<div>
    <h3>УДАЛИТЬ {{ newuser.username }}</h3>
    <p>ВЫ ДЕЙСТВИТЕЛЬНО ХОТИТЕ УДАЛИТЬ?</p>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="УДАЛИТЬ">
    </form>
</div>

{% endblock %}



lab_1/pythonProject/mysite/polls/templates/polls/detail.html
{% extends 'base.html' %}


{% block content %}

<form class="px-10" action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>
            <h1>{{question.question_text}}</h1>
        </legend>
        <p>ПОЛНОЕ ОПИСАНИЕ: {{question.description}}</p>

        {% if error_message %}<p><strong> {{error_message}}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
        <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
        {% endfor %}
    </fieldset>
<input class="border" type="submit" value="ПРОГОЛОСОВАТЬ">
</form>

{% endblock %}

lab_1/pythonProject/mysite/polls/templates/polls/home_page.html
{% extends 'base.html' %}


{% block content %}

{% if latest_question_list %}
<p class="px-10 font-bold">ВОПРОСЫ:
    <ul class="px-10">
        {% for question in latest_question_list %}
        {% if question.was_published_recently %}
        <li><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a>
            <p>КРАТКОЕ ОПИСАНИЕ: {{question.brief_description}}</p>
        </li>
        {% endif %}
        {% endfor %}
    </ul>
        {% else %}
         <p class="py-10 px-10">
             ВОПРОСОВ НЕТ
         </p>
</p>
{% endif %}


{% endblock %}

lab_1/pythonProject/mysite/polls/templates/polls/log_user.html
{% extends 'base.html' %}


{% block content %}
<div class="px-10">
    <h2>ДОБРО ПОЖАЛОВАТЬ {{ user.username }}</h2>

    {% if newuser.photo_avatar %}
        <img src="{{ newuser.photo_avatar.url }}">
    {% else %}
        <div class="non_avatar">
            <h3 id="non_avatar">ДОБАВЬТЕ АВАТАР</h3>
        </div>
    {% endif %}

    {% if newuser == request.user %}
        <a href="./update">РЕДАКТИРОВАНИЕ |</a>
        <a href="./delete">УДАЛЕНИЕ</a>
    {% endif %}
</div>

{% endblock %}



lab_1/pythonProject/mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} = {{ choice.votes }} ГОЛОСА</li>
    {% endfor %}
</ul>
<a  class="border" href="{% url 'polls:detail'  question.id %}">ВЫБРАТЬ ЕЩЕ РАЗ? </a>

lab_1/pythonProject/mysite/polls/templates/polls/update_user.html
{% extends 'base.html' %}

{% block content %}
<form class="px-10" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input class="border" type="submit" value="ОБНОВИТЬ"/>
</form>
{% endblock %}
